controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - optimo_joint1
      - optimo_joint2
      - optimo_joint3
      - optimo_joint4
      - optimo_joint5
      - optimo_joint6
      - optimo_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity