dynamixel:
  device_name: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9BTGF3-if00-port0
  servo_id: 101
  baudrate: 1000000
  set_position_control_mode_on_start: true
  enable_torque_on_start: true

min_jerk:
  duration_sec: 1.0
  command_rate_hz: 100.0
  completion_tolerance_rad: 0.01
