# Default initial positions for optimo's ros2_control fake system

initial_positions:
  optimo_joint1: 0
  optimo_joint2: 3.14
  optimo_joint3: 0
  optimo_joint4: 0
  optimo_joint5: 0
  optimo_joint6: 0
  optimo_joint7: 0
