# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - optimo_arm_controller

  optimo_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - optimo_joint1
      - optimo_joint2
      - optimo_joint3
      - optimo_joint4
      - optimo_joint5
      - optimo_joint6
      - optimo_joint7
    action_ns: follow_joint_trajectory
    default: true