controller_manager:
  ros__parameters:
    update_rate: 100  # Hz


    ft_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

ft_sensor_broadcaster:
  ros__parameters:
    frame_id: "index_ft_sensor"  # Required
    sensor_name: "ft_sensor"

    state_publish_rate: 100.0  # 

    interface_names:
      force:
        x: "force.x"
        y: "force.y"
        z: "force.z"
      torque:
        x: "torque.x"
        y: "torque.y"
        z: "torque.z"

    offset:
      force:
        x: 0.0
        y: 0.0
        z: 0.0
      torque:
        x: 0.0
        y: 0.0
        z: 0.0
