// Copyright 2026
//
// Licensed under the Apache License, Version 2.0.

#pragma once

#include <Eigen/Core>

#include <cstdint>
#include <fstream>
#include <string>

#include "mppi_core/core/mppi_optimizer.hpp"

namespace mppi_core::logging {

struct MppiRolloutLoggerConfig {
  bool enabled{false};
  std::string output_directory{"/tmp/mppi_eval"};
  std::string file_prefix{"mppi"};
  int rollout_log_stride{1};
  int max_logged_horizon_steps{0};
  int flush_every_n_ticks{10};
};

struct MppiTickLogRecord {
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW

  uint64_t tick_index{0};
  double time_s{0.0};
  std::string controller_state;
  std::string phase;

  Eigen::VectorXd q_meas;
  Eigen::VectorXd qdot_meas;
  Eigen::VectorXd tau_meas;

  Eigen::VectorXd q_ref_current;
  Eigen::VectorXd qdot_ref_current;

  Eigen::VectorXd q_cmd;
  Eigen::VectorXd qdot_cmd;
  Eigen::VectorXd tau_cmd;
  Eigen::VectorXd kp;
  Eigen::VectorXd kd;

  Eigen::VectorXd selected_action_qddot;

  double nominal_total_cost{0.0};
  bool command_valid{false};
  bool used_fallback{false};

  int tactile_sensor_count{0};
  int active_tactile_sensor_count{0};
  int active_hemisphere_count_total{0};
  double tactile_total_force_n{0.0};
};

class MppiRolloutLogger {
 public:
  MppiRolloutLogger() = default;

  bool Configure(const MppiRolloutLoggerConfig& config);
  bool enabled() const { return enabled_; }

  void LogTick(const MppiTickLogRecord& record);

  // Logs horizon_index = 1..H. Each row contains trace.states[h], generated by
  // trace.actions[h - 1] with trace.step_costs[h - 1].
  void LogRollout(uint64_t tick_index, double time_s, const RolloutTrace& trace);

  void LogEvent(uint64_t tick_index, double time_s, const std::string& event,
                const std::string& detail);

  void Flush();

 private:
  bool OpenFiles();
  void WriteTickHeader();
  void WriteRolloutHeader();
  void WriteEventHeader();

  MppiRolloutLoggerConfig config_;
  bool enabled_{false};
  bool headers_written_{false};
  uint64_t write_count_{0};

  std::ofstream ticks_file_;
  std::ofstream rollouts_file_;
  std::ofstream events_file_;
};

}  // namespace mppi_core::logging
