offsets:
  - name: thumb_roll
    offset: 0
  - name: thumb_yaw
    offset: 0
  - name: thumb_mcp
    offset: -0.405698776
  - name: thumb_pip
    offset: 9.01407623
  - name: index_mcp
    offset: 7.58239937
  - name: index_pip
    offset: 10.6143665
  - name: middle_mcp
    offset: -0.459105492
  - name: middle_pip
    offset: 0.238994598
