offsets:
  - name: thumb_roll
    offset: 0
  - name: thumb_yaw
    offset: 0
  - name: thumb_mcp
    offset: -0.687609673
  - name: thumb_pip
    offset: 9.15255165
  - name: index_mcp
    offset: 6.91061974
  - name: index_pip
    offset: 8.75009537
  - name: middle_mcp
    offset: -0.0864038467
  - name: middle_pip
    offset: 3.50137329
