offsets:
  - name: thumb_roll
    offset: 0
  - name: thumb_yaw
    offset: 0
  - name: thumb_mcp
    offset: 0.664721489
  - name: thumb_pip
    offset: 10.6841755
  - name: index_mcp
    offset: 6.98233795
  - name: index_pip
    offset: 9.71980667
  - name: middle_mcp
    offset: 0.345426559
  - name: middle_pip
    offset: 1.02254486
