controller_manager:
  ros__parameters:
    update_rate: 1000


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:

    action_monitor_rate: 20.0

    joints:
      - optimo_joint1
      - optimo_joint2
      - optimo_joint3
      - optimo_joint4
      - optimo_joint5
      - optimo_joint6
      - optimo_joint7

    gains:
      optimo_joint1:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 100.0
        ff_velocity_scale: 100.0
      optimo_joint2:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 100.0
        ff_velocity_scale: 100.0
      optimo_joint3:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 100.0
        ff_velocity_scale: 100.0
      optimo_joint4:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 100.0
        ff_velocity_scale: 100.0
      optimo_joint5:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 100.0
        ff_velocity_scale: 100.0
      optimo_joint6:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 100.0
        ff_velocity_scale: 100.0
      optimo_joint7:
        p: 1000.0
        i: 100.0
        d: 10.0
        i_clamp: 100.0
        ff_velocity_scale: 100.0

 
    


    # interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity