# Default initial positions for plato's ros2_control fake system

initial_positions:
  optimo_joint1: 0
  optimo_joint2: 0
  optimo_joint3: 0
  optimo_joint4: 0
  optimo_joint5: 0
  optimo_joint6: 0
  optimo_joint7: 0
  plato_f1_mcp_pitch: 0
  plato_f1_mcp_roll: 0
  plato_f1_pip_pitch: 0
  plato_f2_mcp_pitch: 0
  plato_f2_mcp_yaw: 0
  plato_f2_pip_pitch: 0
  plato_f3_mcp_pitch: 0
  plato_f3_mcp_yaw: 0
  plato_f3_pip_pitch: 0