# Default initial positions for plato_manipulator's ros2_control fake system

initial_positions:
  plato_joint0: 0.0
  plato_joint1: 0.0
  plato_joint2: 0.0
  plato_joint3: 0.0
  plato_joint4: 0.0
  plato_joint5: 0.0
  plato_joint6: 0.0
  plato_joint7: 0.0
  plato_joint8: 0.0