# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - plato_hand_controller

  plato_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - plato_joint0
      - plato_joint1
      - plato_joint2
      - plato_joint3
      - plato_joint4
      - plato_joint5
      - plato_joint6
      - plato_joint7
      - plato_joint8
    action_ns: follow_joint_trajectory
    default: true