# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - optimo_arm_controller
    - plato_hand_controller

  optimo_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - optimo_joint1
      - optimo_joint2
      - optimo_joint3
      - optimo_joint4
      - optimo_joint5
      - optimo_joint6
      - optimo_joint7
  plato_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - plato_f1_mcp_roll
      - plato_f1_mcp_pitch
      - plato_f1_pip_pitch
      - plato_f2_mcp_yaw
      - plato_f2_mcp_pitch
      - plato_f2_pip_pitch
      - plato_f3_mcp_yaw
      - plato_f3_mcp_pitch
      - plato_f3_pip_pitch