# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    optimo_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    plato_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

optimo_arm_controller:
  ros__parameters:
    joints:
      - optimo_joint1
      - optimo_joint2
      - optimo_joint3
      - optimo_joint4
      - optimo_joint5
      - optimo_joint6
      - optimo_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
plato_hand_controller:
  ros__parameters:
    joints:
      - plato_f1_mcp_roll
      - plato_f1_mcp_pitch
      - plato_f1_pip_pitch
      - plato_f2_mcp_yaw
      - plato_f2_mcp_pitch
      - plato_f2_pip_pitch
      - plato_f3_mcp_yaw
      - plato_f3_mcp_pitch
      - plato_f3_pip_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity