# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - hand_controller

  hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - plato_f1_mcp_roll
      - plato_f1_mcp_pitch
      - plato_f1_pip_pitch
      - plato_f2_mcp_yaw
      - plato_f2_mcp_pitch
      - plato_f2_pip_pitch
      - plato_f3_mcp_yaw
      - plato_f3_mcp_pitch
      - plato_f3_pip_pitch