joint_position_controller_node:
  ros__parameters:
    impedance_presets:
      zero:
        stiffness: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        damping:   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      soft:
        stiffness: [2.0, 2.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
        damping:   [0.15, 0.15, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      medium:
        stiffness: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
        damping:   [0.2, 0.2, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
      hard:
        stiffness: [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5]
        damping:   [0.2, 0.2, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
