mppi_motion:
  horizon_steps: 20
  num_rollouts: 256
  dt: 0.01
  temperature: 1.0
  random_seed: 1

  action:
    lower_bound: -4.0
    upper_bound: 4.0
    noise_std: 1.0

  cost:
    q_target_weight: 20.0
    qdot_target_weight: 1.0
    qddot_weight: 0.01
    tau_weight: 0.001
    joint_limit_weight: 2.0
    joint_limit_margin_rad: 0.10

    enable_line_of_action_cost: true
    line_of_action_weight: 5.0
