controller_manager:
  ros__parameters:
    plato_ros_controller:
      type: plato_ros_controller/PlatoRosController

plato_ros_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8
    tactile_topics: []
    compute_impedance_torque: false
