controller_manager:
  ros__parameters:
    plato_ros_controller:
      type: plato_ros_controller/PlatoRosController

plato_ros_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8
    tactile_topics: []
    joint_teleop_command_topic: "~/joint_teleop"
    grasp_teleop_command_topic: "~/grasp_teleop_command"
    grasp_force_reference_topic: "/grasp_force_reference/target_normal_force_n"
    grasp_force_reference_valid_topic: "/grasp_force_reference/reference_valid"
