tasks:
  idle:
    use_current_position: true
    impedance_level: 0.0
    wait_sec: 0.0
    grasp_plan:
      effort_ff: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  dorsal_index_pinch:
    pos_preset_name: dorsal_index_pinch
    impedance_level: 10.0
    wait_sec: 0.5
    grasp_plan:
      effort_ff: [0.0, 0.0, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0]
      grasp_duration_sec: 1.0
