lateral_pinch:
  joint_names: [joint1, joint2, joint3, joint4, joint5, joint6, joint7, joint8]
  position: [1.187, -0.102, -0.04, -0.164, 0.403, 1.034, 0.645, 1.893]
index_pinch:
  joint_names: [joint1, joint2, joint3, joint4, joint5, joint6, joint7, joint8]
  position: [0.00, 0.00, 0.193, -0.265, 0.251, 0.811, 0.884, 1.154]
