plato2:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      plato2_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      aristo_controller:
        type: plato_ros_controller/PlatoRosController

  plato2_joint_state_broadcaster:
    ros__parameters:
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
        - joint7
        - joint8

  aristo_controller:
    ros__parameters:
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
        - joint7
        - joint8

      tactile_topics:
        - /tactile_0/tactile_states
        - /tactile_1/tactile_states
      joint_teleop_command_topic: /plato2/aristo_controller/joint_teleop
      grasp_teleop_command_topic: /plato2/parallel_grasp_controller/commands
      grasp_force_reference_topic: /grasp_force_reference/target_normal_force_n
      grasp_force_reference_valid_topic: /grasp_force_reference/reference_valid
      control_config_yaml_path: "package://aristo_controller/config/aristo.yaml"
      publish_robust_grasp_debug_markers: true
      robust_grasp_debug_marker_topic: ~/robust_grasp_debug_markers
      robust_grasp_debug_frame_id: base_link
