#ifndef PLATO2_CONTROLLERS__JOINT_IMPEDANCE_CONTROLLER_HPP_
#define PLATO2_CONTROLLERS__JOINT_IMPEDANCE_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "realtime_tools/realtime_buffer.hpp"

#include "std_msgs/msg/float64_multi_array.hpp"
#include "plato2_interfaces/msg/impedance_commands.hpp"
// Auto-generated by parameter library
#include "plato2_controllers_parameters.hpp"




namespace plato2_controllers
{
using CmdType = plato2_interfaces::msg::ImpedanceCommands;

class JointImpedanceController : public controller_interface::ControllerInterface
{
public:
  JointImpedanceController();

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

private:
  std::shared_ptr<plato2_controllers::ParamListener> param_listener_;

  plato2_controllers::Params params_;

  size_t dof_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<CmdType>> rt_command_ptr_;
  rclcpp::Subscription<CmdType>::SharedPtr joints_command_subscriber_;

  std::vector<double> current_positions_;
  std::vector<double> current_velocities_;

  bool resize_or_validate(std::vector<double> & param, const std::string & param_name);
};

}  // namespace plato2_controllers

#endif  // PLATO2_CONTROLLERS__JOINT_IMPEDANCE_CONTROLLER_HPP_
