controller_manager:
  ros__parameters:
    update_rate: 1000
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    optimo_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    
    # TODO: Add effort controller
    # plato_effort_controller:
    #   type: effort_controllers/GroupEffortController

optimo_joint_controller:
  ros__parameters:

    action_monitor_rate: 20.0

    joints:
      - optimo_joint1
      - optimo_joint2
      - optimo_joint3
      - optimo_joint4
      - optimo_joint5
      - optimo_joint6
      - optimo_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


