controller_manager:
  ros__parameters:
    update_rate: 1000


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:

    action_monitor_rate: 20.0

    joints:
      - plato_f1_mcp_roll
      - plato_f1_mcp_pitch
      - plato_f1_pip_pitch
      - plato_f2_mcp_yaw
      - plato_f2_mcp_pitch
      - plato_f2_pip_pitch
      - plato_f3_mcp_yaw
      - plato_f3_mcp_pitch
      - plato_f3_pip_pitch


    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
